name: CSM Commit Monitor (Simple)

on:
  schedule:
    # Run every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build CSM
        run: go build -o csm

      - name: Check for new commits
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ./csm --webhook "$DISCORD_WEBHOOK"

    # Note: This version doesn't save tracking data back to repo
    # Each run will check against the config.json baseline
    # If you want persistent tracking, use the main monitor.yml instead
